mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs-concat'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-reboot'
mod 'puppetlabs-powershell'
mod 'puppetlabs-apt'
mod 'samuelson-dockeragent'
mod 'puppetlabs-docker'
